# Generated by Django 4.2.6 on 2023-11-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_medicine_treats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/awesomeAvatar.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
