# Generated by Django 4.2.6 on 2023-11-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='processed_photo',
            field=models.BooleanField(default=False, verbose_name='Обработанное фото'),
        ),
    ]
