# Generated by Django 4.2.6 on 2023-11-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_categoryproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categoryproduct'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
