# Generated by Django 4.2.6 on 2023-11-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_medicine_category_alter_categoryproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='img',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usertestresult',
            name='time',
            field=models.TimeField(),
        ),
    ]
