# Generated by Django 4.2.6 on 2023-12-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_imageproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medicine'),
        ),
    ]
