# Generated by Django 5.0 on 2023-12-18 10:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_imageproduct_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='img',
            field=models.ImageField(blank=True, upload_to=api.models.file_location),
        ),
    ]
