# Generated by Django 5.0 on 2024-01-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_medicine_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicine',
            new_name='Product',
        ),
    ]
