# Generated by Django 5.0 on 2024-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_medicine_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название метода оплаты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание метода оплаты')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/', verbose_name='Логотип магазина')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Валюта')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Налоговая ставка')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Стоимость доставки')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Уведомления по электронной почте')),
                ('payment_methods', models.ManyToManyField(blank=True, to='api.paymentmethod', verbose_name='Методы оплаты')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
    ]
