version: "3.8"

services:
  vue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue
    restart: always
    ports:
      - 8080:8080
    networks:
      - myNetwork
    command: ["npm", "run", "serve"]

networks:
  myNetwork:
